apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"sparkoperator.k8s.io/v1beta2","kind":"SparkApplication","metadata":{"annotations":{},"name":"spark-wordcount","namespace":"default"},"spec":{"driver":{"coreRequest":"100m","cores":1,"memory":"512m","memoryOverhead":"128m","serviceAccount":"spark"},"executor":{"coreRequest":"100m","cores":1,"instances":1,"memory":"512m","memoryOverhead":"128m"},"image":"cloud-course-spark:local","imagePullPolicy":"Never","mainApplicationFile":"local:///opt/spark/work/wordcount.py","mode":"cluster","pythonVersion":"3","restartPolicy":{"type":"Never"},"sparkVersion":"3.4.0","type":"Python"}}
  creationTimestamp: "2026-06-14T19:43:07Z"
  generation: 1
  name: spark-wordcount
  namespace: default
  resourceVersion: "108271"
  uid: 9441386f-f199-4c29-ba23-216fcb7d80dd
spec:
  deps: {}
  driver:
    coreRequest: 100m
    cores: 1
    memory: 512m
    memoryOverhead: 128m
    serviceAccount: spark
  executor:
    coreRequest: 100m
    cores: 1
    instances: 1
    memory: 512m
    memoryOverhead: 128m
  image: cloud-course-spark:local
  imagePullPolicy: Never
  mainApplicationFile: local:///opt/spark/work/wordcount.py
  mode: cluster
  pythonVersion: "3"
  restartPolicy:
    type: Never
  sparkVersion: 3.4.0
  type: Python
status:
  applicationState:
    state: COMPLETED
  driverInfo:
    podName: spark-wordcount-driver
    webUIAddress: 10.107.199.30:4040
    webUIPort: 4040
    webUIServiceName: spark-wordcount-ui-svc
  executionAttempts: 1
  executorState:
    cloudcoursewordcount-5045169ec7a8f247-exec-1: COMPLETED
  lastSubmissionAttemptTime: "2026-06-14T19:43:07Z"
  sparkApplicationId: spark-d74a0a7b8e3848fca7a288b134bbc648
  submissionAttempts: 1
  submissionID: cdadf89b-01f5-4f4b-a534-62585d75fb7b
  terminationTime: "2026-06-14T19:43:30Z"
