apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"sparkoperator.k8s.io/v1beta2","kind":"SparkApplication","metadata":{"annotations":{},"name":"douban-analysis-2executor","namespace":"default"},"spec":{"arguments":["--input","/opt/spark/work/data/douban_movies.csv","--format","csv"],"driver":{"coreRequest":"100m","cores":1,"memory":"1g","memoryOverhead":"256m","serviceAccount":"spark"},"executor":{"coreRequest":"100m","cores":1,"instances":2,"memory":"1g","memoryOverhead":"256m"},"image":"swr.cn-north-4.myhuaweicloud.com/cloud_course/spark:v1","imagePullPolicy":"IfNotPresent","mainApplicationFile":"local:///opt/spark/work/spark_sql_analysis.py","mode":"cluster","pythonVersion":"3","restartPolicy":{"type":"Never"},"sparkVersion":"3.4.3","type":"Python"}}
  creationTimestamp: "2026-06-15T04:50:02Z"
  generation: 1
  name: douban-analysis-2executor
  namespace: default
  resourceVersion: "30388"
  uid: a395fae0-268e-4a25-9677-1584805938ac
spec:
  arguments:
  - --input
  - /opt/spark/work/data/douban_movies.csv
  - --format
  - csv
  deps: {}
  driver:
    coreRequest: 100m
    cores: 1
    memory: 1g
    memoryOverhead: 256m
    serviceAccount: spark
  executor:
    coreRequest: 100m
    cores: 1
    instances: 2
    memory: 1g
    memoryOverhead: 256m
  image: swr.cn-north-4.myhuaweicloud.com/cloud_course/spark:v1
  imagePullPolicy: IfNotPresent
  mainApplicationFile: local:///opt/spark/work/spark_sql_analysis.py
  mode: cluster
  pythonVersion: "3"
  restartPolicy:
    type: Never
  sparkVersion: 3.4.3
  type: Python
status:
  applicationState:
    state: COMPLETED
  driverInfo:
    podName: douban-analysis-2executor-driver
    webUIAddress: 10.247.68.205:4040
    webUIPort: 4040
    webUIServiceName: douban-analysis-2executor-ui-svc
  executionAttempts: 1
  executorState:
    doubansparksqlanalysis-7f0b799ec99d9c44-exec-1: COMPLETED
    doubansparksqlanalysis-7f0b799ec99d9c44-exec-2: COMPLETED
  lastSubmissionAttemptTime: "2026-06-15T04:50:02Z"
  sparkApplicationId: spark-cd55295a72064fe8a954f085f06ba6db
  submissionAttempts: 1
  submissionID: 827e5c0e-600a-43a3-9005-8798267dce8c
  terminationTime: "2026-06-15T04:50:30Z"
